/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajuda;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class ajud extends javax.swing.JFrame {

    /**
     * Creates new form ajud
     */
    public ajud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAjuda = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ComboAjuda = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHelp = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        txtAjuda.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtAjuda.setText("Ajuda");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Confimar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ComboAjuda.setEditable(true);
        ComboAjuda.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ComboAjuda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione sua duvida!", "O que é obrigatório cadastra?", "Dicas essenciais para seu orçamento.", "Como melhorar seu Orçamento Empresarial", "Como cadastrar um cliente?", "Como modificar dados do cliente?", "Como excluir um cliente?", "Como criar um fornecedor?", "Como modificar o fornecedor?", "Como excluir fornecedor?", "Como mudar o seus dados de cadastro?", "Como criar um Novo cadastro?", "Como Modificar os dados do login usuário?", "Como excluir um Usuário?", "Como trocar de usuário?" }));
        ComboAjuda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        txtHelp.setColumns(20);
        txtHelp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtHelp.setRows(5);
        txtHelp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(txtHelp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComboAjuda, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(txtAjuda)
                        .addGap(0, 293, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtAjuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("Selecione sua duvida!")){
        JOptionPane.showMessageDialog(rootPane,"Você ainda não selecionou nada!");
        
    }
        
       else if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("O que é obrigatório cadastra?")){
            txtHelp.setText(
"===============================================================================\n" +
                        "CADASTRO DE CLIENTES\n" +
"Na parte de cadastrar o cliente é obrigatório declarar o nome do seu\n" +
"cliente e o seu ID vai ser gerado automaticamente.\n" +
"===============================================================================\n" +
"\n" +
                       "CADASTRO DE ORÇAMNETO\n" +
"Quando for cadastrar as informações do orçamento, é obrigado a\n" +
"declarar o quantidade de itens e o ID vai ser gerado\n" +
"automaticamente.\n" +
"===============================================================================\n" +
"\n" +
                       "CADASTRO DE PRODUTOS\n" +
"No cadastro de produto é obrigatório declarar a categoria do\n" +
"produto ,unidade media ,preço de venda, a situação e nome do\n" +
"produto.\n" +
"===============================================================================\n" +
"\n" +
                      "CADASTRO DE FORNECEDOR\n" +
"Na parte de cadastrar o fornecedor é obrigado a declarar o nome do\n" +
"fornecedor.\n" +
"===============================================================================\n");
            
        }
        
        else if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("Dicas essenciais para seu orçamento.")){
             txtHelp.setText(
"===============================================================================\n" +
"1. Calcule todas fontes de renda\n" +
"Dentro de fontes de renda, vale lembrar, você deve incluir:\n" +
"# Vendas\n" +
"# Investimentos\n" +
"# Empréstimos\n" +
"# Economias\n" +
"===============================================================================\n" +
"2. Liste os custos fixos\n" +
"Listar despesas fixas é quase automático num orçamento\n" +
"empresarial. Mas, não esqueça de passar por todas:\n" +
"# Aluguel\n" +
"# Salários\n" +
"# Internet\n" +
"# Telefone\n" +
"# Taxas do Governo e Bancos\n" +
"# Hospedagem do site\n" +
"# Ferramentas contratadas\n" +
"# Serviços de contabilidade\n" +
"# Serviços legais\n" +
"# Seguros\n" +
"\n" +
"===============================================================================\n" +
"3. Inclua os custos variáveis\n" +
"Muitas dessas despesas podem ser reduzidas ou ampliadas\n" +
"usando o lucro da empresa. Isso quer dizer que, se sua\n" +
"empresa tiver um desempenho superior ao esperado, você\n" +
"poderá usar fundos extras para investir e permitir que o\n" +
"negócio cresça mais rápido.\n" +
"# Matéria-prima\n" +
"# Água\n" +
"# Gás\n" +
"# Papel e impressão\n" +
"# Luz elétrica\n" +
"# Freelancers\n" +
"# Comissões\n" +
"# Publicidade\n" +
"# Outros custos de Marketing\n" +
"# Transporte\n" +
"# Viagens e Eventos\n" +
"===============================================================================\n" +
"4. Preveja despesas únicas\n" +
"Aqui se trata de definir itens que podem surgir\n" +
"inesperadamente, como a compra de um laptop para substituir\n" +
"o que quebrou, ou outros gastos que podem ser orçados com\n" +
"meses de antecedência. Portanto, contabilize:\n" +
"# Construção\n" +
"# Reformas\n" +
"# Computadores e eletrônicos\n" +
"# Móveis\n" +
"# Material de escritório\n" +
"# Comes &amp; Bebes\n" +
"# Presentes\n" +
"# Consertos\n" +
"===============================================================================\n" +
"5. Reúna tudo\n" +
"Você pode usar uma planilha Excel ou Google Sheets para\n" +
"reunir todos os tipos de gastos e receitas que pontuamos\n" +
"aqui. Mas também pode adotar uma ferramenta de gestão\n" +
"financeira, como o ContaAzul.\n" +
"O importante é que faça isso o quanto antes. Agora que você\n" +
"sabe como fazer um orçamento empresarial, essa tarefa\n" +
"deixou de ser um aborrecimento para se tornar um projeto de\n" +
"infraestrutura que te capacita para tomar decisões financeiras\n" +
"inteligentes. De acordo?\n"
+"===============================================================================");
            
        }
 else if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("Como melhorar seu Orçamento Empresarial")){
      txtHelp.setText(
"1 – Utilize os padrões do ano anterior para o exercício atual.\n" +
"===============================================================================\n" +
"2 – Crie um fluxo de aprovação antes do orçamento chegar em\n" +
"você.\n" +
"===============================================================================\n" +
"3 – Envolva os gestores no trabalho.\n" +
"===============================================================================\n" +
"4 – Fuja do “Esqueci de orçamentar.\n" +
"===============================================================================\n" +
"5 – Automatize cálculos padrões (e evite erros humanos\n" +
"===============================================================================\n" +
"6 – Automatize o Orçamento de Gastos com Pessoal\n" +
"===============================================================================\n" +
"7 – Encurte o ciclo orçamentário\n" +
"===============================================================================\n");
  }
  
 else if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("Como cadastrar um cliente?")){
     new cadastrarcliente.passo1().setVisible(true);
      this.setVisible(false);
    }
    
 else if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("Como modificar dados do cliente?")){
     new modificar_Dados_cliente.passo1().setVisible(true);
      this.setVisible(false);
     
 }
 else if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("Como excluir um cliente?")){
     new Excluir_dados_Cliente.passo1().setVisible(true);
     this.setVisible(false);
 }
 
  else if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("Como criar um fornecedor?")){
      new como_criar_um_fornecedor.passo1().setVisible(true);
      this.setVisible(false);
  }
    
  else if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("Como modificar o fornecedor?")){
      new Como_modificar_o_fornecedor.Passo1().setVisible(true);
      this.setVisible(false);
  }
    
  else if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("Como excluir fornecedor?")){
      new como_excluir_fornecedor.Passo1().setVisible(true);
      this.setVisible(false);
      
  }
  else if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("Como mudar o seus dados de cadastro?")){
      new Como_mudar_o_seus_dados_de_cadastro.Passo1().setVisible(true);
      this.setVisible(false);
  }
   else if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("Como criar um Novo cadastro?")){
       new Como_criar_um_Novo_cadastro.Passo1().setVisible(true);
       this.setVisible(false);
   }
    else if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("Como Modificar os dados do login usuário?")){
       new Como_Modificar_os_dados_do_login_usuário.Passo1().setVisible(true);
       this.setVisible(false);
    }
    else if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("Como excluir um Usuário?")){
        new Como_excluir_um_Usuário.Passo1().setVisible(true);
        this.setVisible(false);
    }
     else if(ComboAjuda.getSelectedItem().toString().equalsIgnoreCase("Como trocar de usuário?")){
         new Como_trocar_de_usuario.Passo1().setVisible(true);
         this.setVisible(false);
     }
    
    
    
  
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboAjuda;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtAjuda;
    private javax.swing.JTextArea txtHelp;
    // End of variables declaration//GEN-END:variables
}
